    { "L"          , OPT_EXIT, {(int*)show_license},      "show license" },
    { "h"          , OPT_EXIT, {(int*)show_help},         "show help", "topic" },
    { "?"          , OPT_EXIT, {(int*)show_help},         "show help", "topic" },
    { "help"       , OPT_EXIT, {(int*)show_help},         "show help", "topic" },
    { "-help"      , OPT_EXIT, {(int*)show_help},         "show help", "topic" },
    { "version"    , OPT_EXIT, {(int*)show_version},      "show version" },
    { "buildconf"  , OPT_EXIT, {(int*)show_buildconf},    "show build configuration" },
    { "formats"    , OPT_EXIT, {(int*)show_formats  },    "show available formats" },
    { "muxers"     , OPT_EXIT, {(int*)show_muxers   },    "show available muxers" },
    { "demuxers"   , OPT_EXIT, {(int*)show_demuxers },    "show available demuxers" },
    { "devices"    , OPT_EXIT, {(int*)show_devices  },    "show available devices" },
    { "codecs"     , OPT_EXIT, {(int*)show_codecs   },    "show available codecs" },
    { "decoders"   , OPT_EXIT, {(int*)show_decoders },    "show available decoders" },
    { "encoders"   , OPT_EXIT, {(int*)show_encoders },    "show available encoders" },
    { "bsfs"       , OPT_EXIT, {(int*)show_bsfs     },    "show available bit stream filters" },
    { "protocols"  , OPT_EXIT, {(int*)show_protocols},    "show available protocols" },
    { "filters"    , OPT_EXIT, {(int*)show_filters  },    "show available filters" },
    { "pix_fmts"   , OPT_EXIT, {(int*)show_pix_fmts },    "show available pixel formats" },
    { "layouts"    , OPT_EXIT, {(int*)show_layouts  },    "show standard channel layouts" },
    { "sample_fmts", OPT_EXIT, {(int*)show_sample_fmts }, "show available audio sample formats" },
    { "colors"     , OPT_EXIT, {(int*)show_colors },      "show available color names" },
    { "loglevel"   , HAS_ARG,  {(int*)opt_loglevel},      "set logging level", "loglevel" },
    { "v",           HAS_ARG,  {(int*)opt_loglevel},      "set logging level", "loglevel" },
    { "report"     , 0,        {(void*)opt_report}, "generate a report" },
    { "max_alloc"  , HAS_ARG,  {(int*)opt_max_alloc},     "set maximum size of a single allocated block", "bytes" },
    { "cpuflags"   , HAS_ARG | OPT_EXPERT, { (int*)opt_cpuflags }, "force specific cpu flags", "flags" },
    { "hide_banner", OPT_BOOL | OPT_EXPERT, {&hide_banner},     "do not show program banner", "hide_banner" },
#if CONFIG_OPENCL
    { "opencl_bench", OPT_EXIT, {(int*)opt_opencl_bench}, "run benchmark on all OpenCL devices and show results" },
    { "opencl_options", HAS_ARG, {(int*)opt_opencl},      "set OpenCL environment options" },
#endif
#if CONFIG_AVDEVICE
    { "sources"    , OPT_EXIT | HAS_ARG, { (int*)show_sources },
      "list sources of the input device", "device" },
    { "sinks"      , OPT_EXIT | HAS_ARG, { (int*)show_sinks },
      "list sinks of the output device", "device" },
#endif
